### ISSUE TITLE
Dosen't accept Certain valid isbn13

### ISSUE THREAD

**Issue by haithem-rihane** [coolaj86/isbnjs#5]
Hi,

The validator can't parse certain Isbn13 such one i copied from amazon books detail
Here's an example:

```
var isbn13a = ISBN.parse('978-2212136029');
isbn13a.isIsbn13();  

```

console return **TypeError: Cannot call method 'isIsbn13' of null**

**Comment by KratosGemini** [comment]
There are two things going on here.
1. The lone hyphen is causing it to not parse as a valid ISBN. It either needs to have no hyphens or have all the hyphens in the hyphenated ISBN format (in this case: 978-2-212-13602-9).
2. The ISBN registration group identifier is 2 for this ISBN. The only groups included the `isbn.js` file are: 0, 1, and 4. There is a `isbn-groups.js` file in the project that contains a full list of groups.  Including that file will solve the missing group problem. I don't know if you are using this in a browser, Node.js, or something else. I'm not a Node expert, but I think there will need to be a little bit of tweaking in order to use it in Node. Or maybe there is some easy way I'm missing.
